---
env:
  browser: true
  commonjs: true
  es2021: true
extends: standard-with-typescript
parser: "@typescript-eslint/parser"
plugins:
- "@typescript-eslint"
overrides:
- files:
  - "*.ts"
  extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  parserOptions:
    project:
    - "./tsconfig.json"
rules:
  "@typescript-eslint/no-misused-promises":
  - error
  - checksVoidReturn: false
